language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install . --quiet
  - pip install nose --quiet
  - pip install speaklater --quiet

script: nosetests

branches:
  only:
    - master
